type IconType = 
'CloseIcon'
|'SaveAltIcon'
|'ArrowDropDownCircleIcon'
|'CameraOutlinedIcon'
|'MonochromePhotosOutlinedIcon'
|'VrpanoOutlinedIcon'  
|'DashboardOutlinedIcon'
|'GamepadOutlinedIcon'
|'ArrowBackIosIcon'
|'PlayCircleIcon'
|'DoDisturbOnIcon'
|'LeakAddIcon'
|'LeakRemoveIcon'
|'NoPhotographyIcon'
|'KeyboardVoiceIcon'
|'MicOffIcon'
;